spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/like_system
    username: db_user
    password: db_password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: redis
      port: 6379
      lettuce:
        pool:
          max-active: 100
          max-idle: 50
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
